In [1]:
#1 Импортировать NumPy под именем np:

import numpy as np

In [2]:
#2 Напечатать версию и конфигурацию:

print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Max/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Max/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Max/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib',

In [3]:
#3 Создать вектор(одномерный массив) размера 10, заполненный нулями

x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4 Создать вектор размера 10, заполненный единицами:

x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
#5 Создать вектор размера 10, заполненный числом 2.5:

x = np.full(10, 2.5)
print(x)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
#6 Как получить документацию о функции numpy.add из командной строки?

#python3 -c "import numpy; numpy.info(numpy.add)"

In [7]:
#7 Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1:

x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#8 Создать вектор со значениями от 10 до 49

x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#9 Развернуть вектор(первый становится последним):

x = np.arange(11)
x = x[::1]
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
#10 Создать матрицу (двумерный массив) 3х3 со значениями от 0 до 8:

x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#11 Найти индексы ненулевых элементов в [1, 2, 0, 0, 4, 0]:

x= np.nonzero([1, 2, 0, 0, 4, 0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [12]:
#12 Создать 3х3 единичную матрицу:

x = np.eye(3, 3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#13 Создать массив 3х3х3 со случайными значениями:

x = np.random.randint((3, 3, 3))
print(x)

[2 0 2]


In [14]:
#14 Создать массив 10х10 со случайными значениями, найти минимум и максимум:

x = np.random.random ((10, 10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)
print()
print(x)

0.02402265584899177 0.9769239206233973

[[0.23314196 0.37575247 0.26021928 0.89981222 0.73223287 0.22482092
  0.21843016 0.6305687  0.8419046  0.47682118]
 [0.04583191 0.19949261 0.64063547 0.45665833 0.70747167 0.18756488
  0.58969167 0.70718515 0.60874621 0.97505033]
 [0.18033949 0.72432836 0.30129825 0.40319509 0.55618852 0.04396504
  0.32197136 0.73281727 0.43937346 0.27363763]
 [0.7516738  0.94814125 0.20075168 0.91943353 0.82802756 0.28261139
  0.52292478 0.29160197 0.72517824 0.64185588]
 [0.26880618 0.46552484 0.97692392 0.94427189 0.65631415 0.35770223
  0.24729665 0.18162993 0.30240396 0.66150113]
 [0.17456238 0.61554753 0.67418189 0.69439058 0.23555098 0.56571344
  0.67139364 0.1523966  0.42680513 0.90941924]
 [0.86382496 0.9702177  0.11822877 0.59036215 0.75327351 0.69470718
  0.26235491 0.7548311  0.02402266 0.85867622]
 [0.33743917 0.97046483 0.45084831 0.85920103 0.42568942 0.17190183
  0.78351108 0.39235564 0.09608865 0.73599167]
 [0.07316288 0.16742369 0.73232543 0.290

In [15]:
#15 Создать случайный вектор размера 30 и найти среднее значение всех элементво:

x = np.random.random(30)
x = x.mean()
print(x)

0.6231334615539585


In [16]:
#16 Создать матрицу с 0 внутри, и 1 на границах:

x = np.ones((10,10))
print(x)
print()
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
#17 Выяснить результат следующих выражений:

x1 = 0 * np.nan
x2 = np.nan == np.nan
x3 = np.inf > np.nan
x4 = np.nan - np.nan
x5 = 0.3 == 3 * 0.1

print(x1)
print(x2)
print(x3)
print(x4)
print(x5)

nan
False
False
nan
False


In [18]:
#18 Создать матрицу 5х5 с 1, 2, 3, 4 под диагональю:

x = np.diag(np.arange(1, 5), k= -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19 Создать матрицу 8х8 и заполнить её в шахматном порядке:

x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#20 Дан масссив размерности (6, 7 , 8). Каков индекс(x,y) сотого элемента?

print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [21]:
#21 Создать матрицу 8x8 и заполнить её вшаматном порядке, используя функцию tile:

x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#22 Перемножить матрицы 5х3 и 3х2:

x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [23]:
#23 Дан массив,поменять знак у элементов, значения которых между 3 и 8:

x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [24]:
#24 Создать матрицу 5х5 со значениями в строках от 0 до 4:

x = np.zeros((5,5))
print(x)
print()
x += np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [25]:
#25 Есть генератор, сделать с его помощью массив:

def generate():
    for i in range(10):
        yield i
        
x = np.fromiter(generate(), dtype = float, count =-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [26]:
#26 Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое:

x = np.linspace(0, 1, 12)[1: -1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [27]:
#27 Отсортировать вектор

x = np.random.random(10)
x.sort()
print(x)

[0.04245061 0.38108619 0.57765369 0.58687601 0.63572599 0.64057226
 0.73182494 0.74270197 0.85158458 0.95455536]


In [28]:
#28 Проверить, одинаковы ли 2 numpy массива:

a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
print(a)
print()
print(b)
print()
equal = np.allclose(a, b)
print(equal)

[1 0 0 0 1]

[1 1 1 1 1]

False


In [97]:
#29 Сделать массив неизменяемым:

#x = np.zeros(10)
#x.flags.writeable = False
#x[0] = 1

In [30]:
#30 Дан массив 10х2 (точки в декартовой системе координат), преобразовать в полярную:

a = np.random.random((10,2))
x, y = a[:, 0], a[:, 1]
b = np.hypot(x, y)
c = np.arctan2(y, x)
print(b)
print()
print(c)

[0.86847245 0.51644154 0.33943033 0.33168154 1.04416691 0.57220591
 0.84612827 1.24042391 0.82451491 0.94509821]

[0.59059335 1.35055625 0.53631169 0.56874657 0.58460376 0.52930941
 0.35823425 0.76376082 0.92082896 0.86183526]


In [31]:
#31 Заменить максимальный элемент на ноль:

x = np.random.random(10)
print(x)
print()
x[x.argmax()] = 0
print(x)

[0.17207866 0.75356355 0.18250833 0.53405776 0.6881196  0.23239501
 0.35818524 0.38570081 0.75392356 0.61851269]

[0.17207866 0.75356355 0.18250833 0.53405776 0.6881196  0.23239501
 0.35818524 0.38570081 0.         0.61851269]


In [32]:
#32 Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

x = np.zeros((10, 10), [('x', float), ('y', float)])
print(x)
print()
x['x'], x['y'] = np.meshgrid(np.linspace(0, 1, 10),
                                            np.linspace(0, 1, 10))
print(x)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)
  (0., 0.) (0., 0.)]]

[[(0.        , 0.        ) (0.11111111, 0.      

In [33]:
#33 Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj)):

x = np.arange(8)
y = x + 0.5
z = 1.0 / np.subtract.outer(x, y)
print(x)
print()
print(np.linalg.det(z))

[0 1 2 3 4 5 6 7]

3638.1636371179666


In [34]:
#34 Найти минимальное и максимальное значение, принимаемое каждым числовым типом NumPy:

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [35]:
#35 Напечатать все значения в массиве:

#np.set_printoptions(threshold=np.nan)
#x = np.zeros((25, 25))
#print(x)

In [36]:
#36 Найти ближайшее к заданному значению число в заданном массиве:

x = np.arange(100)
y = np.random.uniform(0, 100)
index = (np.abs(x-y)).argmin()
print(x)
print()
print(y)
print()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

77.94442022874782

78


In [37]:
#37 Создать структурированный массив, представляющий координату (x, y) и цвет (r, g, b):

#x = np.zeros(10, [('position', [('x', float, 1),
#                                                ('y', float, 1)]),
#                            ('color',      [('r', float, 1),
#                                                ('g', float , 1),
#                                                ('b', float, 1)])])
#print(x)

In [38]:
#38 Дан массив (100, 2) координат, найти расстояние от каждой точки до каждой:

import scipy.spatial

x = np.random.random((10, 2))
d = scipy.spatial.distance.cdist(x, x)
print(d)                     

[[0.         0.78813629 1.08299596 0.76497464 1.04503764 0.2307356
  0.15445974 0.7413183  0.60631254 0.46108489]
 [0.78813629 0.         0.43138475 0.48205103 0.31833303 1.01540539
  0.64876773 0.61447519 0.20176702 0.79587262]
 [1.08299596 0.43138475 0.         0.90857371 0.14843712 1.28640757
  0.92884874 0.54759394 0.50765359 0.89652599]
 [0.76497464 0.48205103 0.90857371 0.         0.77957767 0.97919426
  0.69840678 1.00198096 0.52780648 1.02004492]
 [1.04503764 0.31833303 0.14843712 0.77957767 0.         1.26040949
  0.89396827 0.61492841 0.44342286 0.9240683 ]
 [0.2307356  1.01540539 1.28640757 0.97919426 1.26040949 0.
  0.36875424 0.88388708 0.82831445 0.53223375]
 [0.15445974 0.64876773 0.92884874 0.69840678 0.89396827 0.36875424
  0.         0.60383597 0.45956362 0.3831673 ]
 [0.7413183  0.61447519 0.54759394 1.00198096 0.61492841 0.88388708
  0.60383597 0.         0.47805428 0.38944241]
 [0.60631254 0.20176702 0.50765359 0.52780648 0.44342286 0.82831445
  0.45956362 0.478054

In [39]:
#39 Преобразовать массив из float в int:

x = np.arange(10, dtype=np.int32)
x = x.astype(np.float32, copy = False)

In [40]:
#40 Дан файл:

#1,2,3,4,5
#6,,,7,8
#,,9,10,11

#Как прочитать его?

#x = np.genfromtxt('missing.dat', delimiter=',')

In [41]:
#41 Каков эквивалент функции enumerate для numpy массивов?

x = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [42]:
#42 Сформировать 2D массив с распределением Гаусса:

x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.hypot(x, y)
sigma, mu = 1.0 , 0.0
G = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [43]:
#43 Случайно расположить p элементов в 2D массив:

n = 10
p = 3
x = np.zeros((n, n))
np.put(x, np.random.choice(range(n*n), p, replace = False), 1)

In [44]:
#44 Отнять среднее из кажой строки в матрице:

x = np.random.rand(5, 10)
y = x - x.mean(axis = 1, keepdims = True)
print(x)
print()
print(y)

[[0.31477745 0.29039011 0.01414432 0.77749485 0.39317116 0.87091503
  0.50333853 0.28324859 0.48870292 0.79621074]
 [0.10206562 0.12277077 0.25287727 0.47716569 0.84177189 0.9953612
  0.83095083 0.96761298 0.2582919  0.86674103]
 [0.29381834 0.11259607 0.02025136 0.63981449 0.24113324 0.49527019
  0.64497226 0.94610536 0.42044072 0.29907621]
 [0.36473101 0.98493273 0.33168687 0.78380311 0.46612282 0.80176701
  0.20863847 0.1690636  0.49634894 0.03029238]
 [0.526552   0.41788796 0.29426658 0.62233908 0.02114698 0.7974889
  0.213394   0.05555036 0.29749098 0.8903876 ]]

[[-0.15846192 -0.18284926 -0.45909505  0.30425548 -0.08006821  0.39767566
   0.03009916 -0.18999078  0.01546355  0.32297137]
 [-0.4694953  -0.44879015 -0.31868365 -0.09439522  0.27021097  0.42380028
   0.25938991  0.39605206 -0.31326902  0.29518011]
 [-0.11752948 -0.29875175 -0.39109646  0.22846666 -0.17021459  0.08392236
   0.23362443  0.53475754  0.0090929  -0.11227161]
 [-0.09900769  0.52119404 -0.13205182  0.32006442 

In [45]:
#45 Отсортировать матрицу по n-ому столбцу

x = np.random.randint(0, 10, (3, 3))
n = 1 # нумерация с нуля
print(x)
print()
print(x[x[:, n].argsort()])

[[9 2 9]
 [3 5 8]
 [8 4 2]]

[[9 2 9]
 [8 4 2]
 [3 5 8]]


In [46]:
#46 Определить, есть ли в 2D массиве нулевые столбцы

x = np.random.randint(0, 1, (3, 10))
print((~x.any(axis = 0)).any())

True


In [47]:
#47 Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами):

x = np.ones(10)
print(x)
print()
i = np.random.randint(0, len(x), 20)
print(i)
print()
x += np.bincount(i, minlength = len(x))
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[9 4 2 7 0 6 5 2 3 1 7 8 1 5 7 4 5 5 9 3]

[2. 3. 3. 3. 3. 5. 2. 4. 2. 3.]


In [48]:
#48 Дан массив (w, h, 3) (картинка) dtype = ubyte, посчитать количество различных цветов:

w, h = 16, 16
i = np.random.randint(0, 2, (w, h, 3)).astype(np.ubyte)
f = i[..., 0] * 256 * 256 + i[..., 1] * 256 + i[..., 2]
n = len(np.unique(f))
print(np.unique(i))

[0 1]


In [49]:
#49 Дан четырехмерный массив, посчитать сумму по последним двум осям:

x = np.random.randint(0, 10, (3,4,3,4))
sum = x.reshape(x.shape[:-2] + (-1,)).sum(axis = -1)
print(sum)

[[38 59 66 74]
 [59 42 59 54]
 [49 53 68 64]]


In [50]:
#50 Найти диагональные элементы произведения матриц

#Slow version
#np.diag(np.dot(x, y))

#Fast version
#np.sum(x, y.T, axis = 1)

#Faster version
#np.einsum('ij, ji->i', x, y)

In [51]:
#51 Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением:

x = np.array([1, 2, 3, 4, 5])
nx = 3
x0 = np.zeros(len(x) + (len(x) - 1) * (nx))
x0[::nx + 1] = x
print(x0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [52]:
#52 Поменять 2 строки в матрице:

x = np.arange(15).reshape(3, 5)
print(x)
print()
x[[0, 1]] = x[[1, 0]]
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


In [55]:
#53 Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами).
# Найти множество уникальных отрезков, составляющих все тругольники
x = np.random.randint(0, 100, (10, 3))
f = np.roll(x.repeat(2, axis = 1), -1, axis = 1)
f = f.reshape(len(f) * 3,2)
f = np.sort(f, axis = 1)
g = f.view(dtype = [('p0', f.dtype), ('p1', f.dtype)])
g = np.unique(g)
print(g)

[( 0, 77) ( 0, 83) ( 3, 27) ( 3, 45) ( 3, 47) ( 3, 94) ( 4, 31) ( 4, 60)
 (15, 29) (15, 62) (27, 47) (27, 74) (27, 92) (29, 62) (31, 60) (45, 94)
 (48, 67) (48, 94) (57, 72) (57, 95) (67, 94) (72, 95) (74, 92) (76, 83)
 (76, 84) (77, 83) (80, 80) (80, 85) (83, 84)]


In [56]:
#54 Дан массив C; создать массив A, что np.bincount(A) == C:

C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [57]:
#55 Посчитать среднее, используя плавающее окно

def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n
print(moving_average(np.arange(20),3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [58]:
#56 Дан вектор Z, построить матрицу, первая строка которой (Z[0], Z[1], Z[2],), каждая последующая сдвинута на 1 (последняя (Z[-3], Z[-2], Z[-1]))

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
z = rolling(np.arange(10), 3)
print(z)

# Разобраться позже, почему идёт вперёд, а не по условию задачи

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [59]:
#57 Инвертировать булево значение, поменять знак у числового массива без создания нового

#x = np.random.randint(0 , 2, 100)
#np.logical_not(arr, out=arr)

#x = np.random.uniform(-1.0, 1.0, 100)
#np.negative(arr, out=arr)

In [62]:
#58 Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку p, как вычислить расстояние от p до каждой линии i (P0[i], P1[i])

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis = 1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis = 1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[2.05146598 3.9708223  0.14322717 9.91367415 2.54244876 1.88241322
 1.12114516 1.36483251 5.10548611 8.05544685]


In [64]:
#59 Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе(дополненное значением fill если необходимо)

Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype = Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P - Rs // 2)
Z_stop = (P + Rs // 2) + Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip (R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip (Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 3 5 4 0 3 1 3 1]
 [2 3 6 2 1 0 3 3 5 4]
 [4 7 3 5 1 3 3 8 2 8]
 [6 2 6 3 1 2 4 0 7 4]
 [4 3 0 1 5 8 0 6 6 9]
 [2 2 1 3 2 8 7 5 6 4]
 [7 6 4 9 7 8 0 6 9 4]
 [4 5 1 6 7 5 1 4 7 7]
 [9 4 4 4 3 9 4 4 1 9]
 [9 0 2 4 0 7 6 3 6 8]]
[[0 0 0 0 0]
 [0 7 2 3 5]
 [0 2 3 6 2]
 [0 4 7 3 5]
 [0 6 2 6 3]]


<ipython-input-64-179dc0ee352c>:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [70]:
#60 Посчитать ранг матрицы

x = np.random.uniform(0, 1, (10, 10))
rank = np.linalg.matrix_rank(x)

In [72]:
#61 Найти наиболее частое значение в массиве

x = np.random.randint(0, 10, 50)
print(x)
print()
print(np.bincount(x).argmax())

[0 7 5 8 4 6 3 6 8 4 8 3 9 0 9 8 6 2 8 6 4 5 5 8 5 2 4 1 5 2 0 9 9 4 2 4 8
 3 0 6 9 7 6 5 7 9 4 6 0 8]

8


In [73]:
#62 Извлечь все смежные 3x3 блоки из 10x10 матрицы

x = np.random.randint(0,5,(10,10))
print(x)
print()
n = 3
i = 1 + (x.shape[0] - n)
j = 1 + (x.shape[1] - n)
C = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[2 2 0 2 3 0 1 3 1 1]
 [4 3 3 3 0 4 3 0 4 1]
 [0 4 1 3 1 4 3 2 0 4]
 [0 1 3 0 3 2 2 0 1 3]
 [3 0 1 0 3 2 4 4 1 2]
 [0 2 2 4 0 3 1 0 3 2]
 [3 4 0 4 3 4 0 1 1 4]
 [1 0 3 3 3 2 3 2 2 4]
 [3 1 2 4 3 1 1 2 2 1]
 [4 1 4 1 3 4 2 1 3 1]]

[[[[2 2 0]
   [4 3 3]
   [0 4 1]]

  [[2 0 2]
   [3 3 3]
   [4 1 3]]

  [[0 2 3]
   [3 3 0]
   [1 3 1]]

  [[2 3 0]
   [3 0 4]
   [3 1 4]]

  [[3 0 1]
   [0 4 3]
   [1 4 3]]

  [[0 1 3]
   [4 3 0]
   [4 3 2]]

  [[1 3 1]
   [3 0 4]
   [3 2 0]]

  [[3 1 1]
   [0 4 1]
   [2 0 4]]]


 [[[4 3 3]
   [0 4 1]
   [0 1 3]]

  [[3 3 3]
   [4 1 3]
   [1 3 0]]

  [[3 3 0]
   [1 3 1]
   [3 0 3]]

  [[3 0 4]
   [3 1 4]
   [0 3 2]]

  [[0 4 3]
   [1 4 3]
   [3 2 2]]

  [[4 3 0]
   [4 3 2]
   [2 2 0]]

  [[3 0 4]
   [3 2 0]
   [2 0 1]]

  [[0 4 1]
   [2 0 4]
   [0 1 3]]]


 [[[0 4 1]
   [0 1 3]
   [3 0 1]]

  [[4 1 3]
   [1 3 0]
   [0 1 0]]

  [[1 3 1]
   [3 0 3]
   [1 0 3]]

  [[3 1 4]
   [0 3 2]
   [0 3 2]]

  [[1 4 3]
   [3 2 2]
   [3 2 4]]

  [[4 3 2]
   [2 2 0]
   [2 4

In [77]:
#63 Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i])

# Note: only works for 2d array and value setting using indices

#class Symetric(np.ndarray):
#    def __setitem__(self, (i,j), value):
#        super(Symetric, self).__setitem__((i,j), value)
#        super(Symetric, self).__setitem__((j,i), value)

#def symetric(Z):
#    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

#S = symetric(np.random.randint(0,10,(5,5)))
#S[2,3] = 42
#print(S)

In [78]:
#64 Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). 
#Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [85]:
65# Дан массив 16x16, посчитать сумму по блокам 4x4

x = np.ones((16,16))
k = 4
s = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(x)
print()
print(s)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [86]:
#66 Написать игру "жизнь"

def iterate(x):
    # Count neighbours
    n = (x[0:-2,0:-2] + x[0:-2,1:-1] + x[0:-2,2:] +
         x[1:-1,0:-2]                + x[1:-1,2:] +
         x[2:  ,0:-2] + x[2:  ,1:-1] + x[2:  ,2:])

    # Apply rules
    birth = (n == 3) & (x[1:-1,1:-1]==0)
    survive = ((n == 2) | (n == 3)) & (x[1:-1,1:-1] == 1)
    x[...] = 0
    x[1:-1,1:-1][birth | survive] = 1
    return x

x = np.random.randint(0,2,(50,50))
for i in range(100):
    print(x)
    x = iterate(x)

[[0 1 0 ... 1 1 0]
 [0 1 0 ... 1 0 0]
 [0 1 0 ... 1 0 1]
 ...
 [1 0 0 ... 0 1 0]
 [1 0 1 ... 1 1 0]
 [0 0 1 ... 1 0 1]]
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [

In [87]:
#67 Найти n наибольших значений в массиве

x = np.arange(10000)
np.random.shuffle(x)
n = 5

print (x[np.argpartition(-x,n)[:n]])

[9998 9999 9997 9996 9995]


In [88]:
#68 Построить прямое произведение массивов (все комбинации с каждым элементом)

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [90]:
#69 Даны 2 массива A (8x3) и B (2x2). 
#Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = (c.sum(axis=(1,2,3)) >= b.shape[1]).nonzero()[0]
print(rows)

[0 1 3 4 5 6 7]


In [92]:
#70 Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

x = np.random.randint(0,5,(10,3))
y = np.logical_and.reduce(x[:,1:] == x[:,:-1], axis=1)
z = x[~y]
print(x)
print()
print(z)

[[4 2 4]
 [4 4 0]
 [3 3 3]
 [4 2 2]
 [4 1 3]
 [1 0 1]
 [3 4 1]
 [3 0 2]
 [4 4 3]
 [4 1 0]]

[[4 2 4]
 [4 4 0]
 [4 2 2]
 [4 1 3]
 [1 0 1]
 [3 4 1]
 [3 0 2]
 [4 4 3]
 [4 1 0]]


In [93]:
#71 Преобразовать вектор чисел в матрицу бинарных представлений

x = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(x[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [94]:
#72 Дан двумерный массив. Найти все различные строки

x = np.random.randint(0, 2, (6,3))
t = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(t, return_index=True)
ux = x[idx]
print(ux)

[[0 0 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [96]:
#73 Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

#np.einsum('i->', A)       # np.sum(A)
#np.einsum('i,i->i', A, B) # A * B
#np.einsum('i,i', A, B)    # np.inner(A, B)
#np.einsum('i,j', A, B)    # np.outer(A, B)