In [1]:
# Импортируем моудли

import sys
import numpy as np

In [3]:
#1 Импортировать модуль и проверить версию

import pandas as pd

print(pd.__version__)
print(np.__version__)
print(pd.show_versions(as_json = True))

1.0.5
1.18.5


C:\Users\Max\anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(


{'system': {'commit': None, 'python': '3.8.3.final.0', 'python-bits': 64, 'OS': 'Windows', 'OS-release': '10', 'machine': 'AMD64', 'processor': 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel', 'byteorder': 'little', 'LC_ALL': 'None', 'LANG': 'None', 'LOCALE': 'English_United States.1251'}, 'dependencies': {'pandas': '1.0.5', 'numpy': '1.18.5', 'pytz': '2020.1', 'dateutil': '2.8.1', 'pip': '20.1.1', 'setuptools': '49.2.0.post20200714', 'Cython': '0.29.21', 'pytest': '5.4.3', 'hypothesis': None, 'sphinx': '3.1.2', 'blosc': None, 'feather': None, 'xlsxwriter': '1.2.9', 'lxml.etree': '4.5.2', 'html5lib': '1.1', 'pymysql': None, 'psycopg2': None, 'jinja2': '2.11.2', 'IPython': '7.16.1', 'pandas_datareader': None, 'bs4': '4.9.1', 'bottleneck': '1.3.2', 'fastparquet': None, 'gcsfs': None, 'matplotlib': '3.2.2', 'numexpr': '2.7.1', 'odfpy': None, 'openpyxl': '3.0.4', 'pandas_gbq': None, 'pyarrow': None, 'pytables': None, 'pyxlsb': None, 's3fs': None, 'scipy': '1.5.0', 'sqlalchemy': '1.3.1

In [4]:
#2 Создать объект pandas Series из листа, объекта NumPy, и словаря

src_list = list('abcde')
src_arr = np.arange(5)
src_dict = dict(zip(src_list, src_arr))

s1 = pd.Series(src_list)
s2 = pd.Series(src_arr)
s3 = pd.Series(src_dict)

print(s1)
print(s2)
print(s3)

0    a
1    b
2    c
3    d
4    e
dtype: object
0    0
1    1
2    2
3    3
4    4
dtype: int32
a    0
b    1
c    2
d    3
e    4
dtype: int64


In [6]:
#3 Преобразовать объект Series в DataFrame

# создаем объект Series
s = pd.Series({'a': 'one', 'b': 'two', 'c': 'three'})

# преобразование в DataFrame
s = s.to_frame

print(s)

<bound method Series.to_frame of a      one
b      two
c    three
dtype: object>


In [7]:
#4 Как объединить несколько объектов Series в DataFrame

s1 = pd.Series(list('abcde'))
s2 = pd.Series(np.arange(5))

# Вариант 1
df1 = pd.concat([s1, s2], axis = 1)
print('Вариант 1')
print(df1)
print()

# Вариант 2
df2 = pd.DataFrame({'col1': s1, 'col2': s2})
print('Вариант 2')
print(df2)

Вариант 1
   0  1
0  a  0
1  b  1
2  c  2
3  d  3
4  e  4

Вариант 2
  col1  col2
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4


In [8]:
#5 Присвоить имя индексу объекта Series

s = pd.Series({'a': 1, 'b': 2, 'c': 3})
s.name = 'My_name'
print(s)

a    1
b    2
c    3
Name: My_name, dtype: int64


In [9]:
#6 Получить элементы объекта Series A, которых нет в объекте Series B

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

#Возвращает вместе с индексами
ans = s1[~s1.isin(s2)]

# Возвращает значения
ans2 = np.setdiff1d(s1, s2, assume_unique = False)
print(ans)
print()
print(ans2)

0    1
1    2
2    3
dtype: int64

[1 2 3]


In [11]:
#7 Получить не пересекающиеся элементы в двух объектах Series

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

# Возвращает вместе с индексами

# Получаем объединение Series без повторений
s_union = pd.Series(np.union1d(s1, s2))
# Получаем пересекающиеся данные
s_intersect = pd.Series(np.intersect1d(s1, s2))
# Отбираем все данные, кроме пересекающихся
ans = s_union[~s_union.isin(s_intersect)]

# Возвращает значения
ans2 = np.setxor1d(s1, s2, assume_unique = False)

print(ans2)

[1 2 3 6 7 8]


In [13]:
#8 Получить от объекта Series показатели описательной статистики

state = np.random.RandomState(42)

s = pd.Series(state.normal(10, 5, 25))
pkz = s.describe()
print(pkz)

count    25.000000
mean      9.182460
std       4.782765
min       0.433599
25%       7.188562
50%       8.829315
75%      12.483571
max      17.896064
dtype: float64


In [15]:
#9 Узнать частоту уникальных элементов объекта Series (гистограмма)

# Создаем объект Series функцией c

data = 'abcdefghik'
len_series = 30
s = pd.Series(np.take(list(data), np.random.randint(len(data), size=len_series)))

# Считаем число вхождений
ans = s.value_counts()

print(s)
print()
print(ans)

0     k
1     f
2     f
3     k
4     e
5     e
6     b
7     g
8     b
9     h
10    b
11    d
12    e
13    a
14    f
15    e
16    i
17    a
18    i
19    b
20    i
21    e
22    a
23    g
24    b
25    e
26    g
27    b
28    k
29    k
dtype: object

b    6
e    6
k    4
g    3
f    3
a    3
i    3
h    1
d    1
dtype: int64


In [16]:
#10 Заменить все элементы обекта Series на 'Other', кроме двух наиболее часто встречающихся

state = np.random.RandomState(42)
s = pd.Series(state.randint(low = 1, high = 5, size = 13))
print(s.value_counts())
s[~s.isin(s.value_counts().index[:2])] = 'Other'
print(s)

3    7
1    3
4    2
2    1
dtype: int64
0         3
1     Other
2         1
3         3
4         3
5     Other
6         1
7         1
8         3
9     Other
10        3
11        3
12        3
dtype: object


In [19]:
#11 Создать объект в Series в индексах дата каждый день 2018 года, в значениях случайное значение

#1 Найти сумму всех вторников
#2 Для каждого месяца найти среднее значение

dti = pd.date_range(start='2020-01-01', end='2020-12-31', freq = 'B')
s = pd.Series(np.random.rand(len(dti)), index = dti)

#1
ans1 = s[s.index.weekday == 2].sum()
print('Сумма всех "вторников"', ans1)
print()

#2
ans2 = s.resample('M').mean()
print('Средние значения по месяцам:\n', ans2)
print()

Сумма всех "вторников" 24.278509788194015

Средние значения по месяцам:
 2020-01-31    0.422112
2020-02-29    0.564590
2020-03-31    0.476823
2020-04-30    0.583757
2020-05-31    0.496911
2020-06-30    0.520556
2020-07-31    0.569721
2020-08-31    0.447786
2020-09-30    0.449423
2020-10-31    0.637289
2020-11-30    0.441069
2020-12-31    0.486070
Freq: M, dtype: float64



In [21]:
#12 Преобразовать объект Series в DataFrame заданной формы(shape)

s = pd.Series(np.random.randint(low = 1, high = 10, size = [35]))

# преобразование в reshape
r = (7, 5)

if r[0] * r[1] != len(s):
    sys.exit('Не возможно применить reshape')

df = pd.DataFrame(s.values.reshape(r))

print(df)

   0  1  2  3  4
0  6  4  9  1  6
1  6  8  7  8  4
2  9  2  1  5  1
3  9  8  5  7  6
4  6  5  1  1  6
5  8  8  2  6  5
6  6  5  8  7  7


In [27]:
#13 Найти индексы объекта Series кратные 3

s = pd.Series(np.random.randint(low = 1, high = 10, size =[7]))

# вариант 1 - выдаёт ошибку, разобраться
#ans1 = np.argwhere(s % 3==0).flatten()
#print(ans1)
#print()

# вариант 2
ans2 = s[s %  3 == 0].index
print(ans2)

Int64Index([0, 1, 2, 3], dtype='int64')


In [28]:
#14 Получить данные по индексам объекта Series

s = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
p = [0, 4, 8, 14, 20, 10]

# Вариант 1
ans1 = s[p]
print(ans1)
print()

# Вариант 2 (take - также может использовать многоуровневые массиавы)
ans2 = s.take(p)
print(ans2)

0     a
4     e
8     i
14    o
20    u
10    k
dtype: object

0     a
4     e
8     i
14    o
20    u
10    k
dtype: object


In [29]:
#15 Объединить два объекта Series вертикально и горизонтально

s1 = pd.Series(range(5))
s2 = pd.Series(list('abcde'))

ans_vertical = s1.append(s2)
ans_horizontal = pd.concat([s1, s2], axis = 1)

print(ans_vertical)
print()
print(ans_horizontal)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [34]:
#16 Получить индексы объекта Series A, данные которых содержатся в объекте Series B

s1 = pd.Series([5,3, 2, 1, 4, 11, 13, 8, 7])
s2 = pd.Series([1, 5, 13, 2])

# Вариант 1 (медленный)
ans1 = np.asarray([np.where(i == s1) [0].tolist()[0] for i in s2])
print(ans1)
print()

# Вариант 2 (медленный)
ans2 = np.asarray([pd.Index(s1).get_loc(i) for i in s2])
print(ans2)
print()

#Вариант 3(быстрый) - ошибка
#ans3 = np.argwhere(s1.isin(s2)).flatten()
#print(ans3)

[3 0 6 2]

[3 0 6 2]



In [38]:
#17 Получить объект Series B, который содержит элементы без повторений объекта A

s = pd.Series(np.random.randint(low = 1, high = 10, size = [10]))
ans = pd.Series(s.unique())
print(ans)

0    1
1    7
2    8
3    4
4    2
dtype: int32


In [40]:
#18 Преобразовать каждый символ объекта в верхний регистр 

s = pd.Series(['life', 'is', 'interesting'])

# преобразование данных в Series в строку
s = pd.Series(str(i) for i in s)

# Вариант 1
ans1 = s.map(lambda x: x.title())
print(ans1)
print()

#Вариант 2
ans2 = pd.Series(i.title() for i in s)
print(ans2)

0           Life
1             Is
2    Interesting
dtype: object

0           Life
1             Is
2    Interesting
dtype: object


In [41]:
#19 Рассчитать количество символов в объекте Series

s = pd.Series(['one', 'two', 'three', 'four', 'five'])
# преобразование в строковый тип
s = pd.Series(str(i) for i in s)

# Вариант 1
ans1 = np.asarray(s.map(lambda x: len(x)))
print(ans1)
print()

# Вариант 2
ans2 = np.asarray([len(i) for i in s])
print(ans2)

[3 3 5 4 4]

[3 3 5 4 4]


In [42]:
#20 Найти разность между объектом Series и смещением объекта Series на n

n = 1

s = pd.Series([1, 5, 7, 8, 12, 15, 17])

ans = s.diff(periods = n)

print(ans)

0    NaN
1    4.0
2    2.0
3    1.0
4    4.0
5    3.0
6    2.0
dtype: float64


In [49]:
#21 Преобразовать разные форматы строк объекта Series в доту

s = pd.Series(['2017/01/01', '2015-02-02', '15 Jan 2019'])

# Возможно нестабильное решение, необходимо корректно указать строковые значения, т.к. могут быть перепутаны месяц и день
ans = pd.to_datetime(s)

print(ans)
print()

#21.1 Поскольку работа с датой часто встречается в работе, то см. ещё один пример

# все данные должные иметь одинаковый формат (часто бывает выгрузка из SQL)
s = pd.Series(['14.02.2019', '22.01.2019', '01.03.2019'])

# преобразование в дату
ans = pd.to_datetime(s, format = '%d.%m.%Y')
print(ans)

0   2017-01-01
1   2015-02-02
2   2019-01-15
dtype: datetime64[ns]

0   2019-02-14
1   2019-01-22
2   2019-03-01
dtype: datetime64[ns]


In [56]:
#22 Получить год, месяц, день, день недели, номер дня в году от объекта Series (string)

from dateutil.parser import parse

s = pd.Series(['01 Jan 2018', '02-02-2011', '20120303', '2013/04/04', '2018-12-31'])

# парсим дату и время
s_ts = s.map(lambda x: parse(x, yearfirst = True))

# получаем года
print(s_ts.dt.year)

# получаем месяц
print(s_ts.dt.month)

# получаем дни
print(s_ts.dt.day)

#получаем номер недели
print(s_ts.dt.weekofyear)

# получаем номер дня в году
print(s_ts.dt.dayofyear)

0    2018
1    2011
2    2012
3    2013
4    2018
dtype: int64
0     1
1     2
2     3
3     4
4    12
dtype: int64
0     1
1     2
2     3
3     4
4    31
dtype: int64
0     1
1     5
2     9
3    14
4     1
dtype: int64
0      1
1     33
2     63
3     94
4    365
dtype: int64


In [57]:
#23 Преобразовать даты месяца и года к 7-ому дню

from dateutil.parser import parse

s = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

ans = s.map(lambda x: parse('04' + x))

print(ans)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


In [60]:
#24 Отобрать элементы объекта Series, которые содержат не менее двух гласных

from collections import Counter

s =pd.Series(['Яблоко', 'Orange', 'Plan', 'Python', 'Апельсин', 'Стол', 'Reliance'])
mask = s.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list("aeiouаоиеёэыуюя")]) >= 2)
ans = s[mask]
print(ans)

0      Яблоко
1      Orange
4    Апельсин
6    Reliance
dtype: object


In [61]:
#25 Отобрать е-маилы из объекта Series

# модуль для работы с регулярными выражениями
import re

emails = pd.Series(['test text@test.com', 'test@mail.ru', 'test.2ru', 'test@pp'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2, 4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
ans = emails[mask]
print(ans)

Series([], dtype: object)


In [62]:
#26 Получить среднее значение каждого уникального объекта Series s1 через "маску"другого объекта Series s2

n = 10
s1 = pd.Series(np.random.choice(['dog', 'cat', 'horse', 'bird'], n))
s2 = pd.Series(np.linspace(1, n, n))
ans = s2.groupby(s1).mean()
print(ans)

bird     6.000000
cat      2.666667
dog      5.000000
horse    9.500000
dtype: float64


In [63]:
#27 Найти евклидово расстояние между двумя объектами Series

n = 3

s1 = pd.Series(np.random.randint(low = 1, high = 10, size = [n]))
s2 = pd.Series(np.random.randint(low = 1, high = 10, size = [n]))

ans = np.linalg.norm(s1-s2)
ans2 = sum((s1 - s2) ** 2) ** 0.5
print(ans)
print()
print(ans2)

7.280109889280518

7.280109889280518


In [66]:
#28 Найти индексы локальных максимумов в объекте Series

s = pd.Series([1, 5, 7, 11, 8, 4, 12, 5, 8, 16, 8])
dd = np.diff(np.sign(np.diff(s)))
ans = np.where(dd == -2) [0] + 1
print(ans)

[3 6 9]


In [68]:
#29 Заменить пробелы в наименее часто встречающимся символом

str_test = 'bnb ber kekb dare'

s = pd.Series(list(str_test))
freq = s.value_counts()
least_freq = freq.dropna().index[-1]
''. join(s.replace(' ', least_freq))

'bnbnbernkekbndare'

In [69]:
#30 Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10

s = pd.Series(np.random.randint(low = 1, high = 10, size = [10]), pd.date_range('2018-01-01', periods=10, freq='W-SAT'))
print(s)

2018-01-06    6
2018-01-13    7
2018-01-20    9
2018-01-27    7
2018-02-03    9
2018-02-10    4
2018-02-17    7
2018-02-24    7
2018-03-03    3
2018-03-10    9
Freq: W-SAT, dtype: int32


In [71]:
#31 Заполнить пропущенные даты, значением выше (заполненной даты)

s = pd.Series([2, 5, 8, np.nan], index = pd.to_datetime(['2020-01-01', '2020-01-03', '2020-01-06', '2020-01-08']))
# заполнить предыдущими значениями
ans = s.resample('D').ffill()
# заполнить последующими значениями
ans2 = s.resample('D').bfill()
print(ans)
print()
print(ans2)

2020-01-01    2.0
2020-01-02    2.0
2020-01-03    5.0
2020-01-04    5.0
2020-01-05    5.0
2020-01-06    8.0
2020-01-07    8.0
2020-01-08    NaN
Freq: D, dtype: float64

2020-01-01    2.0
2020-01-02    5.0
2020-01-03    5.0
2020-01-04    8.0
2020-01-05    8.0
2020-01-06    8.0
2020-01-07    NaN
2020-01-08    NaN
Freq: D, dtype: float64


In [72]:
#32 Вычислить автокорреляцию объекта Series 

n = 20

s = pd.Series(np.arange(n))
s = s + np.random.normal(1, 3, n)

autocorr = [s.autocorr(lag = i).round(2) for i in range(n)]

print(autocorr)

[1.0, 0.8, 0.79, 0.89, 0.7, 0.7, 0.81, 0.67, 0.71, 0.74, 0.53, 0.73, 0.77, 0.54, 0.4, 0.73, -0.42, -0.15, -1.0, nan]


C:\Users\Max\anaconda3\lib\site-packages\numpy\lib\function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)
C:\Users\Max\anaconda3\lib\site-packages\numpy\lib\function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
